name:                hermes
version:             0.1.0.0
github:              "MercuryTechnologies/hermes"
license:             BSD-3-Clause
author:              "Ian Duncan"
maintainer:          "ian@mercury.com"
copyright:           "2024 Mercury Technologies"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/semantic-http#readme>

default-extensions:    
- DataKinds
- DeriveGeneric
- DerivingStrategies
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies

dependencies:
- base >= 4.7 && < 5
- charset
- flatparse
- parser-combinators
- bytestring
- case-insensitive
- foldl
- http-types
- hashable
- intern
- mason
- memory
- MonadRandom
- unordered-containers
- validation
- text
- text-short
- time
- transformers
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  hermes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-discover
    - hspec-hedgehog
    - hedgehog
    - hermes

benchmarks:
  hermes-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - hermes
